### ISSUE TITLE
Changing the logs path

### ISSUE THREAD

**Issue by gregolin** [brianmcmichael/SAGU#14]
I would like to change the log path. I use SAGU in Applications folder (OSX), but it saves all logs in the same path, so the 3 files logs are in apps folder. It would be better put them in another path (my user path, for instance).
Thanks.

**Comment by liry** [comment]
Will be introduced in version 0.75.0. See description https://github.com/brianmcmichael/SAGU/wiki/Properties-and-logs-location for more details.

**Comment by cpence** [comment]
Awesome, thanks so much!
