### ISSUE TITLE
Upload complete message window shouldn't expand to fit results

### ISSUE THREAD

**Issue by philosophicles** [brianmcmichael/SAGU#23]
I just finished uploading around 180 files with SAGU in one go, on a Macbook Pro running OS X 10.10 (Yosemite).

The 'Uploaded' dialog box shown when the upload (of all files) is complete expands to fit the set of results.  This meant it was ~180 lines high in my case, which expanded way down below the end of my screen. (The 'OK' button couldn't be reached.)  

Ideally I think the dialog should have constrained dimensions (proportional to screen dimensions) and contain the results in a scrollable text area.

**Comment by philosophicles** [comment]
I don't know much Java, but taking a look at UploadWindow.java it looks as though this window is meant to scroll, so I guess this is a bug rather than a feature request.

**Comment by liry** [comment]
Version 0.74.7 or newer.
