### ISSUE TITLE
Status code 403, InvalidSignatureException when file to upload has Non-ASCII characters in full path

### ISSUE THREAD

**Issue by iluvcapra** [brianmcmichael/SAGU#4]
I believe this is because the upload file's path is being used as x-ams-archive-description, and the string isn't being properly sanitized.  If this string is to be used, it should be URL encoded or ASCII-fied before being set.

It'd probably be better if you were prompting for a description and simply used the path as a default -- some people'd rather not include their full path for security reasons.

**Comment by liry** [comment]
Fixed in 0.74.2 (https://github.com/brianmcmichael/SAGU/commit/4f8c162d1626ebfee9b442ca223acc2c3ef1b8cd).
